# Generated by Django 4.0.3 on 2022-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_icon', models.ImageField(upload_to='photos/%Y/%M/%D/')),
                ('players_count', models.IntegerField()),
                ('top_batsman', models.CharField(max_length=225)),
                ('top_bolower', models.CharField(max_length=225)),
                ('championship_won', models.IntegerField()),
            ],
        ),
    ]
